[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12" }
bevy_asset_loader = "0.19.1"
bevy_egui = { version = "0.24" }
bevy_ggrs = { version = "0.14.0" }
bevy_matchbox = { version = "0.8.0", features = ["ggrs"] }

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
