# width
max_width = 160
array_width = 50
chain_width = 50
fn_call_width = 50
struct_lit_width = 50
attr_fn_like_width = 50
struct_variant_width = 50
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50

# other
group_imports = "StdExternalCrate"
match_arm_blocks = false
where_single_line = true
force_multiline_blocks = true
use_field_init_shorthand = true