[package]
name = "game"
version = "0.1.0"
edition = "2021"

[features]
default = ["stable"]
stable = []

[dependencies]
core = { path = "../core" }
ggrs = { version = "0.10.1" }
anyhow = { version = "1.0.81" }
bevy = { version = "0.13" }
bevy_asset_loader = { version = "0.20.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.10.0", features = ["ron"] }
bevy_egui = { version = "0.26.0" }
bevy_ggrs = { version = "0.15.0" }
bevy_matchbox = { version = "0.9.0", features = ["ggrs"] }
bytemuck = { version = "1.15.0" }
clap = { version = "4.5.3", features = ["derive"] }
rapier2d = { version = "0.18.0", features = ["enhanced-determinism"] }
serde = { version = "1.0.197" }
derivative = "2.2.0"
rand = "0.8.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy_ggrs = { version = "0.15.0", features = ["wasm-bindgen"] }
