[package]
name = "core"
version = "0.1.0"
edition = "2021"

[features]
default = ["stable"]
stable = []

[dependencies]
core_derive = { path = "../core_derive" }
ggrs = { version = "0.11.1" }
anyhow = { version = "1.0.98" }
bevy = { version = "0.16" }
bevy_asset_loader = { version = "0.23.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.13.0", features = ["ron"] }
bevy_egui = { version = "0.34.1" }
bevy_ggrs = { version = "0.18.0" }
bevy_matchbox = { version = "0.12.0", features = ["ggrs"] }
bytemuck = { version = "1.23.0" }
clap = { version = "4.5.39", features = ["derive"] }
rapier2d = { version = "0.26.1", features = ["enhanced-determinism"] }
serde = { version = "1.0.219" }
derivative = "2.2.0"
rand = "0.9.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy_ggrs = { version = "0.18.0", features = ["wasm-bindgen"] }
